[versions]
kotlin = "2.1.20"
compose-plugin = "1.8.0"
kotlinx-serialization = "1.8.0"
mpfilepicker = "3.1.0"
gradle-download = "5.6.0"
juniversalchardet = "2.5.0"

[libraries]
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
mpfilepicker = { module = "com.darkrockstudios:mpfilepicker", version.ref = "mpfilepicker" }
juniversalchardet = { module = "com.github.albfernandez:juniversalchardet" , version.ref = "juniversalchardet"}

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
gradle-download-task = { id = "de.undercouch.download", version.ref = "gradle-download" }
